apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: my-cluster
  region: ap-northeast-2
  version: "1.26"

vpc:
  id: vpc-0a09ccb20b05a7d83
  subnets:
    private:
      a:
        id: subnet-001d01e275f3db94a
      b:
        id: subnet-0624f7d4d30fbf26b

privateCluster:
  enabled: true
  additionalEndpointServices:
    - "autoscaling"
    - "logs"

managedNodeGroups:
  - instanceType: t3.small
    name: addon
    desiredCapacity: 2
    minSize: 2
    maxSize: 10
    privateNetworking: true
  - instanceType: t3.small
    name: app
    desiredCapacity: 2
    minSize: 2
    maxSize: 10
    privateNetworking: true


cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

iam:
  withOIDC: true
