apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
        v1: c
    spec:
      readinessGates:
        - conditionType: target-health.alb.ingress.k8s.aws/hello_hello_80
      containers:
      - name: hello
        image: nginxdemos/hello:plain-text
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "20"]
